name: Build and Publish Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:

    runs-on:
      - in-service
      - builder

    steps:

      - name: Fix permissions
        run: sudo chmod 777 -R $GITHUB_WORKSPACE

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images and output the image name
        id: strings
        shell: bash
        run: |
          # Output the image name
          set pipefail
          DOCKER_CI_IMAGE=$(.github/build-docker-images.sh | tail -n 1)
          echo "DOCKER_CI_IMAGE $DOCKER_CI_IMAGE"
          echo "docker-image=$DOCKER_IMAGE" >> "$GITHUB_OUTPUT"